# Generated by Django 3.2.9 on 2021-11-29 07:01

import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('report', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('reported_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('blacklist', models.IntegerField(max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCheck',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=255)),
                ('caste', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=3)),
                ('mother_tongue', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('annual_income', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('employed_in', models.CharField(max_length=255)),
                ('photo_count', models.IntegerField(max_length=255)),
                ('profile_created_by', models.CharField(max_length=255)),
                ('marital_life', models.CharField(max_length=255)),
                ('brother', models.IntegerField(max_length=3)),
                ('sister', models.IntegerField(max_length=3)),
                ('p_age', models.CharField(max_length=255)),
                ('p_marital_status', models.CharField(max_length=255)),
                ('p_mother_tongue', models.CharField(max_length=255)),
                ('p_religion', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-religion'],
            },
        ),
        migrations.CreateModel(
            name='AdminPanel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=3)),
                ('mobile_no', models.IntegerField(max_length=10, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-email'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
